name: soagmb
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  animate_do: ^4.2.0
  cached_network_image: ^3.4.0
  carousel_slider: ^5.0.0
  conditional_builder_null_safety: ^0.0.6
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_stripe: ^11.5.0
  flutter_paypal_payment: ^1.0.8
  flutter_svg: ^2.1.0
  fluttertoast: ^8.2.12
  full_screen_image: ^2.0.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.1
  image_picker: ^1.1.2
  location: ^8.0.0
  logger: ^2.4.0
  modal_progress_hud_nsn: ^0.5.1
  popover: ^0.3.0+1
  readmore: ^3.0.0
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  flutter_native_splash: ^2.4.4
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/core/global/assets/images/
    - lib/core/global/style/map_styles.json
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
